name: "Node Code Formatter"
description: "Formats your code automatically! Runs `npm run <lint/format>` on file changes."
author: "MarvinJWendt"
branding:
  icon: award
  color: orange
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
