name: 'Node Code Linter'
description: 'Automatically lints your code'
author: 'MarvinJWendt'
branding:
  icon: award
  color: orange
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
